### ISSUE TITLE
Trying to skip to step using wz-disabled causes error

### ISSUE THREAD

**Issue by russTbaker** [angular-wizard/angular-wizard#180]
Hi,

First of all, thanks for taking the time to create this tool, I've found it very useful. I have a use case where the wizard loads a series of pre-conditions and then presents the user with a list of options. Each option relates to a step in the wizard beyond where this list is presented. Each of those steps has the "wz-disabled" attribute and I set it to false when I want to enter that step. Fore example:

**HTML**
`<wz-step wz-title="This is my step" wz-disabled="{{myStep_disabled}}">`

and the controller code:

**Controller**
`$scope.goToMyStep = function(){
      $scope.myStep_disabled = false;
      WizardHandler.wizard().goTo('This is my step');
}`

This results in the following error:

`angular.js:12783 TypeError: Cannot read property 'canenter' of null
    at f (angular-wizard.min.js:7)
    at Scope.a.goTo (angular-wizard.min.js:7)
    at goTo (angular-wizard.min.js:7)
    at Scope.$scope.goToMyStep (myController.js:53)
    at fn (eval at <anonymous> (angular.js:13628), <anonymous>:4:332)
    at expensiveCheckFn (angular.js:14610)
    at callback (angular.js:24071)
    at Scope.$eval (angular.js:16359)
    at Scope.$apply (angular.js:16459)
    at HTMLAnchorElement.<anonymous> (angular.js:24076)`

Did I miss something?

Thanks in advance!

**Comment by GrowMon** [comment]
Hi,

Any word on this issue?

**Comment by PhilipeGatis** [comment]
Hi.
Sorry for my english.
This error is because in the first moment, the object wizard load all the steps with no disable tag and you try acess the steps with this tag, this steps are loaded after. I believe, in source code uses directive ng-if to do this. You can add $watch in scope to observe the number of steps and use one if clause to compare with the number of steps totals.
Example:

$scope.$watch(function() {
        return WizardHandler.wizard();
    }, function (wizard) {
        if (wizard) {
            $scope.$watch(wizard.totalStepCount() , function () {
               if (wizard.totalStepCount() === totalsteps) {
                   --enter all steps loaded
                }
            });
        }
    });

**Comment by jacobscarter** [comment]
@russTbaker the issue is as @PhilipeGatis stated, you are attempting to access the step before a digest cycle has added the step to the steps array.  You can wrap the `goTo()` in a `$timeout` forcing a digest cycle to run or you can add the watch like mentioned above.  Hope that helps.
