### ISSUE TITLE
canexit calling on all steps but setted in one

### ISSUE THREAD

**Issue by joaopaulonobrega** [angular-wizard/angular-wizard#181]
Hi, first, tnks for this angular module.

I'm by setting in one step , however, all other call , and even load the page it's called , I think I'm doing something wrong, but I'm not finding what may be, can someone help me? 

```
<wizard on-finish="finishedWizard()"> 
    <wz-step wz-title="Cotação">          
        <div ng-include="'Ui/View/Quote/Steps/Cotacao.html'"></div>
    </wz-step>
    <wz-step  wz-title="Confirmação dos dados" canexit="validateStep()">
        <div ng-include="'Ui/View/Quote/Steps/ConfirmacaoDados.html'"></div>
    </wz-step>
    <wz-step wz-title="Aceite">
        <div ng-include="'Ui/View/Quote/Steps/Aceite.html'"></div>
    </wz-step>
    <wz-step wz-title="Finalizar">
        <div ng-include="'Ui/View/Quote/Steps/Finalizar.html'"></div>
    </wz-step>
</wizard>
```

the scope function

```
$scope.validateStep = function(){  
    if(!$scope.quoteVM.confirmacaoDados.dadosParaFatura.isento) {
        if(!$scope.quoteVM.confirmacaoDados.dadosParaFatura.rgIe > 0) {

            return false;
        }
    }

    return true;
};
```

**Comment by jacobscarter** [comment]
I'm sorry I don't understand your question, what is the error or wrong behavior that is happening?

**Comment by joaopaulonobrega** [comment]
I'm validating only one step, however, the function I used to validate this step is being called when I call any other step , and even when I load the page it is called , I believe the right, it was the function is called only the validated step, but is not this happening . The same happened here [#177](https://github.com/mgonto/angular-wizard/issues/177)

**Comment by jacobscarter** [comment]
I will create a jsFiddle and try to reproduce this, I'll get back to your shortly.

**Comment by joaopaulonobrega** [comment]
I created one, however usually it works in my development environment does not happen so, = (

[jsFiddle ](https://jsfiddle.net/jpnobrega/0pjqkgau/26/)

**Comment by joaopaulonobrega** [comment]
I could simulate , I created a contactor to increase each time the function is called, in loading it already increases the variable [jsFiddle](https://jsfiddle.net/jpnobrega/0pjqkgau/34/)

**Comment by joaopaulonobrega** [comment]
I managed to simulate the function to validate , it Is set only in the second step , however it is called in other steps as well, and even the loading , I put writing on the island, every time it is called , see:
 [jsFiddle](https://jsfiddle.net/jpnobrega/0pjqkgau/48/)

**Comment by joaopaulonobrega** [comment]
Only loading was called 3 times before reaching the step that will be validated.


![sem titulo](https://cloud.githubusercontent.com/assets/8898223/15469063/32c7c9f2-20be-11e6-9bf6-0509e42dcdea.png)

**Comment by lindamarieb** [comment]
I am getting the same behaviour.

**Comment by wbyoko** [comment]
Seems to need a function reference `someFn` not an expression to be run `someFn()`

The way it's currently being done isn't the idiomatic way to do it but that is what works.

**Comment by jacobscarter** [comment]
Per @wbyoko comment, you are improperly using the `canexit` attribute, reference the method, do not envoke it. `canexit="validateStep"` not `canexit="validateStep()"`
