### ISSUE TITLE
How to implement the angular-wizard in isolated scope? 

### ISSUE THREAD

**Issue by dreamerNcoder** [angular-wizard/angular-wizard#183]
Hi, 

I have tried implementing the angular-wizard with isolated scope, and while doing so, I am not sure how to inject the controller function to an button inside the template of wizard steps. 

Please guide me.

Thanks

**Comment by jacobscarter** [comment]
@dreamerNcoder can you please provide a code example of your issue.  thanks.

**Comment by LearnGrowAndShare** [comment]
Sorry for delay in response, I have found out that the set up was incorrect for us .. now it's working
