### ISSUE TITLE
Translate Wz-title

### ISSUE THREAD

**Issue by Akawan** [angular-wizard/angular-wizard#184]
Hi, 

When I translate wz-title, for exemple  `<wz-step wz-title="{{ 'searchActivity' | translate }}">` the wizard display the key. 

But in code source it's ok 
![2016-06-09 17_25_46-localhost_23456_ _addactivity_2207128793](https://cloud.githubusercontent.com/assets/4621135/15935369/4a0fd418-2e67-11e6-9091-4fb0c9160d41.png)

![2016-06-09 17_25_35-localhost_23456_ _addactivity_2207128793](https://cloud.githubusercontent.com/assets/4621135/15935375/4f64d21a-2e67-11e6-9a3d-aa6fa70990f9.png)

**Comment by jacobscarter** [comment]
Can you provide a jsFiddle or Plunker that I can look at?

**Comment by salimchami** [comment]
Hello,
I'm facing the same problem. 
I Think that we can put two way binding on title variable (`wzTitle: '='` instead of `wzTitle: '@'`)  and don't use an intermedate variable for the title... 
`$scope.title = $scope.wzTitle;`

**Comment by salimchami** [comment]
Hi! 
Here is the [plunker](https://plnkr.co/edit/0Mf8Vd7LG6aqIWu9Ca1b?p=preview) !

**Comment by jacobscarter** [comment]
This issue will be fixed and closed when #203 is merged
