### ISSUE TITLE
WizardHandler.wizard().goTo does not update the step indicator

### ISSUE THREAD

**Issue by hemrajdev24000** [angular-wizard/angular-wizard#214]
When I use the WizardHandler.wizard().goTo('title') in my controller I go the current step in the wizard but the indicator does not show the previous steps as green. Is this a known issue?

**Comment by jacobscarter** [comment]
Yes it is, you would need to toggle the editMode on the wizard, instructions on how to do that can be found in the README.md. 

Hope this helps, if you want further functionality I would be happy to merge a PR.
