### ISSUE TITLE
Seperate HTML and Controller for each wz-step

### ISSUE THREAD

**Issue by Vandu07** [angular-wizard/angular-wizard#216]
I am using angular-wizard in ma application.
For each step am using separate html and controller.
Is there any way to pass data from one step(controller) to next step (controller).
Is there any directive values which I can set ?I have tried using canenter and canexit. It didn't work.While passing from one step to another the corresponding controllers are not called.Any help would be deeply appreciated

<wz-step wz-title="Step1">
                <div ng-controller="step1Controller as vm" ng-include="'modules/views/step1.html'">

                </div>
</wz-step>

**Comment by jacobscarter** [comment]
you have access to the `context` object on the wizard, you can see examples of this on the enterValidation and exitValidation example in the README.md, or you can use and Angular Service https://docs.angularjs.org/guide/services
