### ISSUE TITLE
Go to a completed step on clicking each step title/nav element

### ISSUE THREAD

**Issue by Vandu07** [angular-wizard/angular-wizard#217]
I am using angular-wizard in my appplication.
I would like to navigate to an edited/completed step. 
Is there anyway I can do it ?

Eg: Suppose if I had edited till step 3 and if I wish to navigate to first step on clicking the title of first step directly from the wizard element?

**Comment by jacobscarter** [comment]
You can currently do this.  For example, in the demo navigate to step 3, then click the green circle for step 1 and you will navigate back to it

http://angular-wizard.github.io/angular-wizard/
