### ISSUE TITLE
Check if form fields are valid before going to next step

### ISSUE THREAD

**Issue by eatshootrock** [angular-wizard/angular-wizard#218]
Hello I'm quite new to AngularJS and to Angular Wizard. 

My wizard contains 4 steps. Each steps have their own form content. I want to see/check if the form fields are valid before proceeding to the next step. I believe I can use canexit but i don't know how to see if my forms fields have valid inputs. 

I want to create a function that would check if the form fields are valid before going to the next step.

 HTML
-------
<wizard on-finish="finishedWizard()" indicators-position="top" template="app/views/wizard-test.html">
    <form name="detailsForm" novalidate>

        <wz-step wz-title="stepOne" canexit="exitStepOne">
            <div class="content-panel">
                <div class="content-panel-body">
                    <h2>This is step 1</h2>
                    <input name="firstname" ng-model="donateDetails.firstname" type="text" class="form-control" id="StepOneFirstname" placeholder="Firstname" ng-required="true">
                    <input name="lastname" ng-model="donateDetails.lastname" type="text" class="form-control" id="StepOneFirstname" placeholder="Firstname" ng-required="true">
                    <input name="email" ng-model="donateDetails.email" type="text" class="form-control" id="StepOneFirstname" placeholder="Firstname" ng-required="true">
                  
                    <div class="wizard-steps-nav">
                        <button wz-next value="Next" type="button" class="btn btn-primary btn-lg">Next</button>
                    </div>
                </div>
            </div>
        </wz-step>

        <wz-step wz-title="stepTwo" canexit="exitStepTwo">
            <div class="content-panel">
                <div class="content-panel-body">
                    <h2>This is step 2</h2>
                    <input name="address" ng-model="donateDetails.address" type="text" class="form-control" id="StepOneFirstname" placeholder="Firstname" ng-required="true">
                    <input name="postal" ng-model="donateDetails.postal" type="text" class="form-control" id="StepOneFirstname" placeholder="Firstname" ng-required="true">
                    <input name="country" ng-model="donateDetails.country" type="text" class="form-control" id="StepOneFirstname" placeholder="Firstname" ng-required="true">

                    <div class="wizard-steps-nav">
                        <button wz-previous value="Previous" type="button" class="btn btn-default btn-lg">Previous</button>
                        <button wz-next value="Next" type="button" class="btn btn-primary btn-lg">Next</button>
                    </div>
                </div>
            </div>
        </wz-step>

        <wz-step wz-title="stepThree" canexit="exitStepthree">
            <div class="content-panel">
                <div class="content-panel-body">
                    <h2>This is step 3</h2>
                    <div class="wizard-steps-nav">
                        <button wz-previous value="Previous" type="button" class="btn btn-default btn-lg">Previous</button>
                        <button wz-next value="Next" type="button" class="btn btn-primary btn-lg">Confirm</button>
                    </div>
                </div>
            </div>
        </wz-step>

        <wz-step wz-title="stepFour">
            <div class="content-panel">
                <div class="content-panel-body">
                    <h2>This is step 3</h2>
                    <div class="wizard-steps-nav">
                        <button wz-previous value="Previous" type="button" class="btn btn-default btn-lg">Previous</button>
                        <button wz-finish type="submit" value="Finish" type="button" class="btn btn-primary btn-lg">Donate</button>
                    </div>
                </div>
            </div>
        </wz-step>
    </form>
</wizard>

Controller
-----------

    $scope.exitStepOne = function() {
        if ($scope.donateDetails.firstname.$valid) {
          console.log("done with step 1");
          return true;
        } else {
             console.log("not yet completed step 1");
            return false;

        }
    };

    $scope.exitStepTwo = function() {
        console.log("done with step 2");
        return true;
    };

    $scope.exitStepThree = function() {
        console.log("done with step 2");
        return true;
    };

**Comment by jacobscarter** [comment]
@eatshootrock you can use angular's ngForm as you mentioned, https://docs.angularjs.org/api/ng/directive/form Or you can set up you own custom validation, it is really up to you.  Read the ngForm docs for specifics on that.
