### ISSUE TITLE
Multy wizard in one controller

### ISSUE THREAD

**Issue by diyaa-hamza** [angular-wizard/angular-wizard#219]
I tried to add more than one wizard in one controller but I got an error once I tried to go to next()

` WizardHandler.wizard().next()`

error message

> Cannot read property 'next' of undefined

**Comment by suyalcinkaya** [comment]
+1

**Comment by suyalcinkaya** [comment]
Naming the wizard worked for me.

in HTML;
```html
<wizard name="wizardName" ........
```
in controller;
```js
WizardHandler.wizard("wizardName").next();
```

**Comment by jacobscarter** [comment]
@diyaa-hamza naming the wizard is the proper way to do it as @suyalcinkaya mentioned
