### ISSUE TITLE
Facing issue in nz-step with ng-repeat

### ISSUE THREAD

**Issue by VishwanathCR** [angular-wizard/angular-wizard#221]
Hi,

I have tried using <wz-step> with ng-repeat, so on page load it works as expected but when the array (eg: datatables) got updated then it is keep on appending new steps at the end (instead of replacing existing wz-steps with the new wz-steps as per new updated array). Also I have checked that the array is getting updated as expected.

Example:

<wizard>
<wz-step>
" 'datatables' array is getting updated here"
</wz-step>
<wz-step ng-repeat="datatable in datatables">
"input fields based on values inside datatable"
</wz-step>
</wizard>

So, Is there any option to remove (reset) my existing steps (except first step, if it is possible) [$scope.steps], and replace it as per updated array.

Please guide me.

Thanks

**Comment by pankajsammal29** [comment]
I also have the same issue, were you able to find any solution for it?

**Comment by VishwanathCR** [comment]
@pankajsammal29 , If you reset the `scope.steps` array (which is internally used inside angular-wizard) on change then it works. Unfortunately, there is no such API exists to reset the `scope.steps` array.
You can update it to latest version, where you can Add/Remove steps.

Hope it helps.

**Comment by jacobscarter** [comment]
@VishwanathCR solution will work, also you can specify step order with the ` wz-order="1"` attribute. the wz-order attribute can be $index of the array you are repeating and that should solve your issue.
