### ISSUE TITLE
Add 'wizard:stepChanged' event to docs

### ISSUE THREAD

**Issue by gmanriqueUy** [angular-wizard/angular-wizard#222]
Hi. I noticed that the emitted event **wizard:stepChanged** is not documented. I think it would be nice to have this on docs.

**Comment by gmanriqueUy** [comment]
Would you merge if I make a PR about this?

**Comment by jacobscarter** [comment]
@gmanriqueUy Yes please make the PR and we will get it merged, make sure to read the CONTRIBUTE.md file.

**Comment by gmanriqueUy** [comment]
@jacobscarter this issue can be closed. ;)
