### ISSUE TITLE
how to make disabled steps visible but not selectable

### ISSUE THREAD

**Issue by gino8080** [angular-wizard/angular-wizard#226]
is it possible to make a disabled step VISIBLE but NOT selectable?

I want the disabled step to remain in the step list in the navigation, BUT no selectable, 

so if I have 4 steps
and the 3rd is disabled

i'll see all 4 steps on navigation bar
when i complete the 2nd I'll go directly to the 4th

hope i explained :)

thank you

**Comment by jacobscarter** [comment]
you can use the canEnter method on the step to stop a user from entering it if you don't want them to.
