### ISSUE TITLE
Calling on-finish at the 'second-last' step?

### ISSUE THREAD

**Issue by ibnYusrat** [angular-wizard/angular-wizard#232]
Hello,

Is there anyway to call the 'on-finish' function just before the final step so that I can show the 'results' of their input on the 'last step' ?

I am trying to find a config before implementing something on my own. 

Please help..

**Comment by jacobscarter** [comment]
You can utilize the canEnter function or canExit function of the previous step, or you can watch the currentStep property and trigger changes based on that.  Hope this helps.
