### ISSUE TITLE
Cannot even load html and canexit called twice

### ISSUE THREAD

**Issue by vijayaKeesara** [angular-wizard/angular-wizard#234]
I cannot load html when I am using when using http://cdn.jsdelivr.net/angular.wizard/latest/angular-wizard.min.js . I am missing something?

I could able to load my html page when I am using http://cdn.jsdelivr.net/angular.wizard/0.6.0/angular-wizard.min.js. 0.6.0 has issue method calling twice when I am on step2.

Please help

**Comment by jacobscarter** [comment]
See README for updated CDN instructions.
