### ISSUE TITLE
wizard().goTo() not behaving as expected

### ISSUE THREAD

**Issue by unluckynelson** [angular-wizard/angular-wizard#242]
Great library, thank you. When I want to use goto to send the user to the last page, the previous steps does not go green and is therefore not clickable. In my use case I need an edit button on a already completed wizard, in case they made a mistake and want to edit something on a previous page.
Could the goto function be adjusted to mark al the previous steps as completed?

**Comment by jacobscarter** [comment]
you editMode to toggle all steps into an "editable" state. see the README.md for instruction on how.

https://github.com/angular-wizard/angular-wizard/blob/master/README.md

**Comment by unluckynelson** [comment]
Hi Jacob

 

Thank you but the Readme is not clear on what value (mode) should be, a string or a boolean?

Also, nowhere in the readme is there an explanation or example of what EditMode is or how to use EditMode.

How would I set a specific steps’ EditMode, or is it set globally?

 

Thanks

Regards

Johan

**Comment by jacobscarter** [comment]
@unluckynelson I will update the README, (mode) would be a boolean and this is a global setting that applies to all steps.
