### ISSUE TITLE
setEditMode is not a function

### ISSUE THREAD

**Issue by asder707** [angular-wizard/angular-wizard#248]
I´m using wizardHandler like a service and the function "WizardHandler.wizard().setEditMode(true)", have an error:
![image](https://user-images.githubusercontent.com/22712532/27044159-a1bab1a4-4f6a-11e7-9c8a-644133aa0429.png)

i´m using te same sintax in the documentation and the others finctions works perfectly.

**Comment by jacobscarter** [comment]
If you look at your angular-wizard JS code what version does in say at the banner at the top.

![example](https://user-images.githubusercontent.com/3640740/27044331-0e95b468-4f52-11e7-9dc4-c1780b5bb5e8.jpg)

**Comment by asder707** [comment]
was a version problem, i update to te latest and works, thanks!
