### ISSUE TITLE
IE issue in steps

### ISSUE THREAD

**Issue by kashifmustafa** [angular-wizard/angular-wizard#45]
Hi, 
This wizard working exactly as described in all browsers except IE. All steps are click-able in internet explorer when wizard is not in edit mode.It should not be click-able in save mode[not edit mode] because it follow the next button not steps. I agree in edit mode all steps are click-able and working fine in IE too. I am using IE 9. So please help me on this ASAP.
Thanks Advance.

**Comment by jacobscarter** [comment]
Looking into this after next release, see #111
